### ISSUE TITLE
Add option or example of how to also add them automatically to CONTRIBUTORS.md

### ISSUE THREAD

**Issue by thadguidry** [actions/first-interaction#17]
**Problem summary:**
It is often necessary to maintain a `CONTRIBUTORS.md` file for many open source projects.
Often when a first PR or ISSUE is created, someone on the team will have to manually add them to the projects' `CONTRIBUTORS.md` file.

**Requested method:**
This should be possible to automate as part of the `actions/first-interaction`.

Internally, perhaps something like this could work (brainstorming):

`echo ${{ GITHUB_ACTOR }} >> CONTRIBUTORS.md`

where some argument option within the first-interaction could be passed to allow appending to the `CONTRIBUTORS.md` file or not.

```
<snip>
with:
  repo-token: $${{ secrets.GITHUB_TOKEN }}
  issue-message: "Thank you!"
  pr-message: "Your awesome! Thanks for this PR!"
  add-contributor: CONTRIBUTORS.md
```

**Alternative method:**
Another separate action could be developed that does this in another step, perhaps it could be called `actions/add-contributor@1` ?
