### ISSUE TITLE
Not sure markdown works

### ISSUE THREAD

**Issue by Serhioromano** [actions/first-interaction#67]
Here is my workflow.

```yml
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    name: Greet new participant
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '##Welcome!\n\nThank you for finding time to write an issue and make this extension better. I`ll appreciate if you find some time to [rate this extension here](https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details).\n\nI`ll get back to your ASAP.'
        pr-message: '##Welcome!\n\nThank you very match for your contribution. I very appreciate it. Please find some time to [rate this extension here](https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details).\n\nI`ll get to this PR ASAP.'
```

I know greeting text is not perfect, but it does not apply markdowd. Please look this issue, this one contain what is produced by action.
https://github.com/Serhioromano/vscode-gitflow/issues/1
