### ISSUE TITLE
Workflow displaying error: yaml: line 11: did not find expected key

### ISSUE THREAD

**Issue by qJake** [actions/first-interaction#8]
I committed a greeting action via the main Actions homepage (one of the templates) and customized the messages.

```yaml
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, thanks for opening your first issue! 🙂 Be sure to check out the contribution guidelines if you haven't already. Thanks!'
        pr-message: 'Hey, congratulations on your first pull request for HACC! 🎉'
```

On the Actions tab for a commit, a few things are off:

* The "runs on" field says "push", but should say "pull_request, issues"
* It says the file is invalid, but this is an OOTB example

![image](https://user-images.githubusercontent.com/652006/63821238-d368d280-c911-11e9-894f-9c5ec6420ac7.png)

What am I doing wrong, or is this a bug with Actions since it's still in beta?

**Comment by damccorm** [comment]
This works if you use double quotes instead of single quotes:
```
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, thanks for opening your first issue! 🙂 Be sure to check out the contribution guidelines if you haven't already. Thanks!"
        pr-message: "Hey, congratulations on your first pull request for HACC! 🎉"
```

@jclem do you know why this is getting a validation error (or who this should get routed to)?
